### ISSUE TITLE
adding contributors section in readme

### ISSUE THREAD

**Issue by rajeshpanjiyar** [CodeTrophs/MarchCode#214]
this will show the valuable **contributors** in the readme section. All new contributors would be added automatically so no need to update this issue time to time.
- I am a participant in GSSoC'21
 I want to work on this so I request you to **assign** me this issue.

**Comment by aryasoni98** [comment]
This project is not a part of GSoC21 . If you still want to contribute on this project you can but the contribution not be counted in GSSoC21 . @rajeshpanjiyar

**Comment by rajeshpanjiyar** [comment]
No problem I even want to work on this. Can I be assigned?

**Comment by aryasoni98** [comment]
@rajeshpanjiyar Okay Go Head
