### ISSUE TITLE
Error in Day 18 java code

### ISSUE THREAD

**Issue by nikita-jain-01** [CodeTrophs/MarchCode#336]
I want to correct my code. Please assign it to me.

**Comment by shubhigupta991** [comment]
Which code? Show SS

**Comment by nikita-jain-01** [comment]
![Screenshot (1462)](https://user-images.githubusercontent.com/72670446/113107077-18a56280-9221-11eb-8e6e-60585e868cf3.png)


In this code I have only printed 2D matrix not an upper triangle matrix..

**Comment by shubhigupta991** [comment]
ok go ahead
